server:
  port: 8110
  servlet:
    context-path: /order

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?allowMultiQueries=true&serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      # 连接池配置
      initial-size: 2
      min-idle: 1
      max-active: 3
      # 连接等待超时时间
      max-wait: 10000
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com:
      springboot:
        mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl